import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "../app/_trpc/Provider";
import AsideBar from "../components/asideBar/AsideBar";
import { NextAuthProvider } from "../app/NextAuthProvider";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <Provider>
            <AsideBar />
            {children}
          </Provider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
